export const coreTypes = {
	UPDATE_AUTHENTICATION: 'UPDATE_AUTHENTICATION',
	SET_LOADING: 'SET_LOADING',
	SET_IS_MOBILE: 'SET_IS_MOBILE',
};

export const userTypes = {
	UPDATE_PROFILE_DATA: 'UPDATE_PROFILE_DATA',
};