export default {
	SET_LOADING: 'SET_LOADING',
	SET_IS_MOBILE: 'SET_IS_MOBILE',
	SET_OS: 'SET_OS',
	SET_CATEGORY: 'SET_CATEGORY',
	SET_GIFT: 'SET_GIFT',
	SET_SUBSCRIBE: 'SET_SUBSCRIBE',
	SET_LIBRARY: 'SET_LIBRARY'
};
